config/routes.rb
Rails.application.routes.draw do
  
  resources :tipo_celulas

  get 'relatorios/index'

  get 'relatorios/aniversariantes'

  get 'relatorios/geral'

  resources :trilhos

  resources :celulas do

    get :gerenciar

    get :adicionar_membro

    get :salvar_membro

    get :remover_membro

    get :salvar_lider_em_treinamento

    get :remover_lider_em_treinamento

    get :adicionar_lider

    get :salvar_lider

    get :remover_lider

    get :adicionar_supervisor

    get :salvar_supervisor

    get :remover_supervisor

    get :adicionar_cordenador

    get :salvar_cordenador

    get :remover_cordenador

    get :relatorios

    resources :encontro_semanals, :path => "encontro_semanais" do

      get :enviar

      get :receber

    end

  end

  resources :igrejas

  resources :pessoas do

    get :trilhos

    get :adicionar_trilho

    post :salvar_trilho

    delete :remover_trilho 
    
  end

  devise_for :users
  
  resources :usuarios do

    get :redefinir_senha

    get :logar_como
  
  end 

  get 'home/index'

  get "home/nao_autorizado"

  root 'home#index'

  
end

app/models/celula.rb
class Celula
  include Mongoid::Document
  include Mongoid::Timestamps

  field :nome, type: String, :default => ""
  field :data_criacao, type: Date
  field :logradouro, type: String, :default => ""
  field :numero, type: String, :default => ""
  field :bairro, type: String, :default => ""
  field :cidade, type: String, :default => ""
  field :estado, type: String, :default => ""
  field :cep, type: String
  field :dia, type: String
  field :hora, type: String, :default => "19"
  field :minutos, type: String, :default => "00"

  field :ativo, type: Boolean, default: true

  belongs_to :igreja
  has_many :membros_da_celula, inverse_of: :celula_que_e_membro, class_name: "Pessoa"
  has_many :lideres_em_treinamento_da_celula, inverse_of: :celula_que_e_lider_em_treinamento, class_name: "Pessoa"
  has_and_belongs_to_many :lideres_da_celula, inverse_of: :celulas_que_e_lider, class_name: "Pessoa"
  has_and_belongs_to_many :supervisores_da_celula, inverse_of: :celulas_que_e_supervisor, class_name: "Pessoa"
  has_and_belongs_to_many :cordenadores_da_celula, inverse_of: :celulas_que_e_cordenador, class_name: "Pessoa"
  has_many :encontro_semanals

  validates_presence_of :nome, :logradouro, :numero, :bairro, :cidade, :estado, :hora, :minutos, :dia, :igreja_id
  validates_uniqueness_of :nome, :scope => [:igreja_id]

  before_save :maiusculas_sem_acentos

  def maiusculas_sem_acentos
    # if self.nome != nil
    #   self.nome = self.nome.upcase
    #   self.nome = self.nome.remover_acentos 
    # end

    if self.nome != "" and self.nome != nil
      self.nome = self.nome.upcase
      self.nome = self.nome.remover_acentos
    end

    if self.logradouro != "" and self.logradouro != nil
      self.logradouro = self.logradouro.upcase
      self.logradouro = self.logradouro.remover_acentos
    end

    if self.bairro != "" and self.bairro != nil
      self.bairro = self.bairro.upcase
      self.bairro = self.bairro.remover_acentos
    end

    if self.cidade != "" and self.cidade != nil
      self.cidade = self.cidade.upcase
      self.cidade = self.cidade.remover_acentos
    end

    if self.estado != "" and self.estado != nil
      self.estado = self.estado.upcase
      self.estado = self.estado.remover_acentos
    end

    if self.estado != "" and self.estado != nil
      self.estado = self.estado.upcase
      self.estado = self.estado.remover_acentos
    end

  end

end

app/controllers/celulas_controller.rb
class CelulasController < ApplicationController

  before_action :set_celula, only: [:show, :edit, :update, :destroy]

  load_and_authorize_resource :class=>"Celula", except: :create

  # GET /celulas
  # GET /celulas.json
  def index
    @celulas = Celula.accessible_by(current_ability)
  end

  # GET /celulas/1
  # GET /celulas/1.json
  def show
  end

  # GET /celulas/new
  def new
    @celula = Celula.new
  end

  # GET /celulas/1/edit
  def edit
  end

  # POST /celulas
  # POST /celulas.json
  def create
    @celula = Celula.new(celula_params)

    respond_to do |format|
      if @celula.save
        format.html { redirect_to @celula, notice: @@msgs }
        format.json { render :show, status: :created, location: @celula }
      else
        flash[:danger] = @@msge
        format.html { render :new }
        format.json { render json: @celula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /celulas/1
  # PATCH/PUT /celulas/1.json
  def update
    respond_to do |format|
      if @celula.update(celula_params)
        format.html { redirect_to @celula, notice: @@msgs }
        format.json { render :show, status: :ok, location: @celula }
      else
        flash[:danger] = @@msge
        format.html { render :edit }
        format.json { render json: @celula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /celulas/1
  # DELETE /celulas/1.json
  def destroy #  -----------------------------------> DESATIVAR / ATIVAR
    if @celula.ativo == true
      @celula.ativo = false
    else
      @celula.ativo = true
    end
    if @celula.save!
      flash[:success] = @@msgs
    else
      flash[:dager] = @@msge
    end

    redirect_to celulas_url
  end

  def gerenciar 
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
  end

  def adicionar_membro
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoas = Pessoa.accessible_by(current_ability).pessoas_sem_celula
  end

  def salvar_membro
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    if @pessoa.adicionar_membro_na_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_adicionar_membro_url(@celula)
    end
  end

  def remover_membro
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    if @pessoa.remover_membro_da_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_adicionar_membro_url(@celula)
    end
  end
  #########################################################

  def salvar_lider_em_treinamento
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    if @pessoa.adicionar_lider_em_treinamento_na_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_gerenciar_url(@celula)
    end
  end

  def remover_lider_em_treinamento
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    if @pessoa.remover_lider_em_treinamento_da_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_adicionar_membro_url(@celula)
    end
  end

  #########################################################
  def adicionar_lider
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoas = Pessoa.accessible_by(current_ability).nao_e_lider_desta_celula(@celula)
  end

  def salvar_lider
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    if @pessoa.adicionar_lider_na_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_adicionar_lider_url(@celula)
    end
  end

  def remover_lider
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    #@pessoa.celula_que_e_membro = nil
    if @pessoa.remover_lider_da_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_adicionar_lider_url(@celula)
    end
  end
  ###################################

  def adicionar_supervisor
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoas = Pessoa.accessible_by(current_ability).nao_e_supervisor_desta_celula(@celula)
  end

  def salvar_supervisor
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    if @pessoa.adicionar_supervisor_na_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_adicionar_supervisor_url(@celula)
    end
  end

  def remover_supervisor
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    #@pessoa.celula_que_e_membro = nil
    if @pessoa.remover_supervisor_da_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_adicionar_supervisor_url(@celula)
    end
  end
  ##################################

  def adicionar_cordenador
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoas = Pessoa.accessible_by(current_ability).nao_e_cordenador_desta_celula(@celula)
  end

  def salvar_cordenador
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    if @pessoa.adicionar_cordenador_na_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_adicionar_cordenador_url(@celula)
    end
  end

  def remover_cordenador
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
    @pessoa = Pessoa.accessible_by(current_ability).find(params[:pessoa_id])

    #@pessoa.celula_que_e_membro = nil
    if @pessoa.remover_cordenador_da_celula(@celula)
      flash[:success] = @@msgs
      redirect_to celula_gerenciar_url(@celula)
    else
      flash[:danger] = @@msge
      redirect_to  celula_adicionar_cordenador_url(@celula)
    end
  end


  def relatorios 
    @celula = Celula.accessible_by(current_ability).find(params[:celula_id])
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_celula
      @celula = Celula.accessible_by(current_ability).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def celula_params
      params.require(:celula).permit(:nome, :data_criacao, :logradouro, :numero, :bairro, :cidade, :estado, 
                                     :cep, :dia, :hora, :minutos, :ativo, :igreja_id, supervisores_da_celula_ids: [])
    end
end

app/helpers/celulas_helper.rb
module CelulasHelper
end

app/views/celulas/_form.html.erb
<%= simple_form_for @celula do |f| %>
  
  <div class="row">
    <div class="col-md-6">
      <%= f.input :nome %>    
    </div>
    <div class="col-md-6">
      <%= f.input :data_criacao, :input_html=>{:class=>'data', :value=>@celula.data_criacao.to_s_br} %>   
    </div>
  </div>
  
  <div class="row">
    <div class="col-md-6">
      <%= f.input :logradouro %>
    </div>
    <div class="col-md-6">
      <%= f.input :numero %>  
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :bairro %>
    </div>
    <div class="col-md-6">
      <%= f.input :cidade %>      
    </div>
  </div>
    
  <div class="row">
    <div class="col-md-6">
      <%= f.input :estado %>
    </div>
    <div class="col-md-6">
      <%= f.input :cep, :input_html=>{:class=>'cep'} %> 
    </div>
  </div>

  <div class="row">
    <div class="col-md-4">
      <%= f.input :dia, :collection => ["SEGUNDA", "TERCA", "QUARTA", "QUINTA", "SEXTA", "SABADO", "DOMINGO"], :input_html => {:class=>"input-medium", :required=>true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :hora, :collection => 00..23, :input_html => {:class=>"input-mini", :required => true} %>
    </div>
    <div class="col-md-4">
      <%= f.input :minutos, :collection => ["00","10","15","20","30","40","45","50"], :input_html => {:class=>"input-mini", :required => true} %>
    </div>
  </div>
  
  <% if current_user.igreja_id != nil %>
    <%= f.input :igreja_id, :as => :hidden, :input_html => {value: current_user.igreja.id} %>
  <% else %>
    <%= f.input :igreja_id, :label=>"Igreja", :collection=>Igreja.accessible_by(current_ability).order_by([:nome, :asc]).collect {|i| [i.nome, i.id]}, as: :select, :input_html => {:class=>"col-xs-2", :required=>true}  %>  
  <% end %>

  <% if current_user.supervisor_nao_master_nao_adm_nao_sec %>
    <div class="row">
      <div class="col-md-6">
        <div class="hidden">
          <%= f.input :supervisores_da_celula_ids, :label=>"Supervisor da Celula", :collection=>Pessoa.where(:id=>current_user.pessoa_id).collect {|i| [i.nome, i.id]}, as: :check_boxes, :input_html=>{:checked => true} %>
        </div>

        <% if @celula.supervisores_da_celula_ids.blank? %>
          <div class="alert alert-info" role="alert">
            <a href="#" class="alert-link">Você será adicionado como supervisor desta celula!</a>
          </div>
        <% end %>
      </div>
      <div class="col-md-6">
        
      </div>
    </div>
       
  <% end %>
  
  

  <br/>

  <div class="form-actions">
    <%= f.button :submit, "Salvar", :class => 'btn btn-primary' %>
    <%= link_to "Cancelar",
                celulas_path, :class => 'btn btn-default' %>
  </div>        
<% end %>

app/views/celulas/adicionar_cordenador.html.erb
<%= titulo_pagina("Adicionar Novo Coordenador","") %>

<table id="coordenadores" class="display table table-hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td></td>
        <td>
           <%= link_to "Adicionar", celula_salvar_cordenador_url(@celula,:pessoa_id => pessoa.id), :class=>"btn btn-success" %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to link_icone('voltar'), celula_gerenciar_path(@celula), :class=>'btn btn-default' %>

app/views/celulas/adicionar_lider.html.erb
<%= titulo_pagina("Adicionar Novo Lider","") %>

<table id="lideres" class="display table table-hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td></td>
        <td>
           <%= link_to "Adicionar", celula_salvar_lider_url(@celula,:pessoa_id => pessoa.id), :class=>"btn btn-success" %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to link_icone('voltar'), celula_gerenciar_path(@celula), :class=>'btn btn-default' %>

app/views/celulas/adicionar_membro.html.erb
<%= titulo_pagina("Adicionar Novo Membro","") %>

<table id="naomembro" class="display" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th>Ações</th>
      
    </tr>
  </thead>
  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td></td>
        <td><%= link_to "Adicionar", celula_salvar_membro_url(@celula, :pessoa_id=>pessoa.id), :class=>"btn btn-success" %></td>
        
      </tr>
    <% end %>
  </tbody>

</table>

<%= link_to link_icone('voltar'), celula_gerenciar_path(@celula), :class=>'btn btn-default' %>

app/views/celulas/adicionar_supervisor.html.erb
<%= titulo_pagina("Adicionar Novo Supervisor","") %>

<table id="supervisores" class="display table table-hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nome</th>
      <th></th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @pessoas.each do |pessoa| %>
      <tr>
        <td><%= pessoa.nome %></td>
        <td></td>
        <td>
           <%= link_to "Adicionar", celula_salvar_supervisor_url(@celula,:pessoa_id => pessoa.id), :class=>"btn btn-success" %> 
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to link_icone('voltar'), celula_gerenciar_path(@celula), :class=>'btn btn-default' %>

app/views/celulas/edit.html.erb
<%- model_class = Celula -%>
<%= titulo_pagina("Editar Celula","") %>
<%= render :partial => 'form' %>

app/views/celulas/gerenciar.html.erb
<%- model_class = Celula -%>
<%= titulo_pagina("Gerenciando Celula: #{@celula.nome}","") %>
<br/>
<table id="membros" class="display table table-hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Nome</th>
      <th>Posição na Celula</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    
    <% @celula.cordenadores_da_celula.each do |x| %>
      <tr>
        <td><%= x.nome %></td>
        <td>COORDENADOR</td>
        <td>
          <% if can? :remover_cordenador, @celula %>
            <%= link_to link_icone('remover'), celula_remover_cordenador_url(@celula, :pessoa_id => x.id), :class=>'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>  

    <% @celula.supervisores_da_celula.each do |x| %>
      <tr>
        <td><%= x.nome %></td>
        <td>SUPERVISOR</td>
        <td>
          <% if can? :remover_supervisor, @celula%>
            <%= link_to link_icone('remover'), celula_remover_supervisor_url(@celula, :pessoa_id => x.id), :class=>'btn btn-danger' %>
          <% end %>  
        </td>
      </tr>
    <% end %>

    <% @celula.lideres_em_treinamento_da_celula.each do |x| %>
      <tr>
        <td><%= x.nome %></td>
        <td>LIDER EM TREINAMENTO</td>
        <td>
          <% if can? :remover_lider_em_treinamento, @celula %>
            <%= link_to link_icone('remover'), celula_remover_lider_em_treinamento_url(@celula, :pessoa_id => x.id), :class=>'btn btn-danger' %>
          <% end %>
        </td>
        
      </tr>
    <% end %>

  	<% @celula.lideres_da_celula.each do |x| %>
      <tr>
        <td><%= x.nome %></td>
        <td>LIDER</td>
        <td>
          <% if can? :remover_lider, @celula %>
            <%= link_to link_icone('remover'), celula_remover_lider_url(@celula, :pessoa_id => x.id), :class=>'btn btn-danger' %> 
          <% end %>
        </td>
      </tr>
    <% end %>

    <% @celula.membros_da_celula.each do |x| %>
      <tr>
        <td><%= x.nome %></td>
        <td>MEMBRO</td>
        <td>
          <% if can? :remover_membro, @celula %>
            <%= link_to link_icone('remover'), celula_remover_membro_url(@celula, :pessoa_id => x.id), :class=>'btn btn-danger' %>
          <% end %>
          <% if can? :salvar_lider_em_treinamento, x %>
            <%= link_to 'Tornar Lider em Treinamento', celula_salvar_lider_em_treinamento_url(@celula, :pessoa_id => x.id), :class=>'btn btn-success' %>          
          <% end %>    
        </td>
      </tr>
    <% end %>

  
  </tbody>
</table>

<table class="table table-responsive">
	<tbody>
		<tr>
			<td>

				<% if can? :adicionar_membro, @celula %>
          <%= link_to "Adicionar Membro", celula_adicionar_membro_path(@celula), :class=>'btn btn-success' %>&nbsp;
        <% end %>
        <% if can? :adicionar_lider, @celula %>
          <%= link_to "Adicionar Lider", celula_adicionar_lider_path(@celula), :class=>'btn btn-success' %>&nbsp;
        <% end %>
        <% if can? :adicionar_supervisor, @celula %>
          <%= link_to "Adicionar Supervisor", celula_adicionar_supervisor_path(@celula), :class=>'btn btn-success' %>&nbsp;
        <% end %>
        <% if can? :adicionar_cordenador, @celula %>
          <%= link_to "Adicionar Coordenador", celula_adicionar_cordenador_path(@celula), :class=>'btn btn-success' %>
        <% end %>
      </td>
    </tr>
</tbody>
</table>

<br/>
<%= link_to link_icone('voltar'), celulas_path, :class=>'btn btn-default' %>

app/views/celulas/index.html.erb
<%- model_class = Celula -%>
<%= titulo_pagina("Listagem de Celulas","") %>

<table id="celulas" class="display table table-hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th>Participantes</th>
      <th>Relatórios</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    <% @celulas.each do |celula| %>
      <tr>
        <td><%= celula.nome %></td>
        <% 
          cont = 0
          cont = cont + celula.membros_da_celula.count 
          cont = cont + celula.lideres_em_treinamento_da_celula.count
          cont = cont + celula.lideres_da_celula.count
        %> 
        <td><%= cont %></td>
        <%
          tod = celula.encontro_semanals.count
          rec = celula.encontro_semanals.where(:status=>"RECEBIDO").count
        %>
        <td><%= rec %>/<%= tod %></td>
        <td>
            <% if celula.ativo == true %>
              
              <%= link_to link_icone('detalhes'),
                        celula_path(celula), :class => 'btn' %>
              
              <% if can? :update, celula %>
                <%= link_to link_icone('editar'),
                        edit_celula_path(celula), :class => 'btn btn-default' %>
              <% end %>
              
              <% if can? :gerenciar, Celula %>
                <%= link_to link_icone("gerenciar"), celula_gerenciar_path(celula), :class=>"btn btn-default" %> 
              <% end %>

              <% if can? :read, EncontroSemanal %>
                <%= link_to link_icone("relatorios"), celula_encontro_semanals_path(celula), :class=>"btn btn-default" %> 
              <% end %>

              <% if can? :delete, Celula %>
                <%= link_to link_icone('desativar'), celula_path(celula), :class=>"btn btn-danger", method: :delete, data: { confirm: 'Você está certo disso?' } %> 
              <% end %>
          <% else %>            
            <% if can? :delete, Celula %>
              <%= link_to link_icone('ativar'), celula_path(celula), :class=>"btn btn-success", method: :delete, data: { confirm: 'Você está certo disso?' } %> 
            <% end %> 
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<% if can? :create, Celula %>
  <%= link_to link_icone('nova'),
            new_celula_path,
            :class => 'btn btn-primary' %>
<% end %>

app/views/celulas/new.html.erb
<%- model_class = Celula -%>
<%= titulo_pagina("Nova Celula","") %>
<%= render :partial => 'form' %>

app/views/celulas/relatorios.html.erb
<%- model_class = Celula -%>
<%= titulo_pagina("Relatorios da Celula: #{@celula.nome}","") %>
<br/>
<table id="relatorios" class="display table table-hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Data</th>
      <th></th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    
    <% @celula.cordenadores_da_celula.each do |x| %>
      <tr>
        <td><%= x.nome %></td>
        <td></td>
        <td>
          <% if can? :remover_cordenador, @celula %>
            <%= link_to link_icone('remover'), celula_remover_cordenador_url(@celula, :pessoa_id => x.id), :class=>'btn btn-danger' %>
          <% end %>
        </td>
      </tr>
    <% end %>  
  
  </tbody>
</table>

<br/>
<%= link_to link_icone('voltar'), celulas_path, :class=>'btn btn-default' %>

app/views/celulas/show.html.erb
<%- model_class = Celula -%>
<%= titulo_pagina("Detalhes da Celula","") %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @celula.nome %></dd>
  <dt><strong>Data Criação:</strong></dt>
  <dd><%= @celula.data_criacao.to_s_br %></dd>
  <dt><strong><%= model_class.human_attribute_name(:logradouro) %>:</strong></dt>
  <dd><%= @celula.logradouro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:numero) %>:</strong></dt>
  <dd><%= @celula.numero %></dd>
  <dt><strong><%= model_class.human_attribute_name(:bairro) %>:</strong></dt>
  <dd><%= @celula.bairro %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cidade) %>:</strong></dt>
  <dd><%= @celula.cidade %></dd>
  <dt><strong><%= model_class.human_attribute_name(:estado) %>:</strong></dt>
  <dd><%= @celula.estado %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cep) %>:</strong></dt>
  <dd><%= @celula.cep %></dd>
  <dt><strong>Funcionamento:</strong></dt>
  <dd><%= @celula.dia %>, <%= @celula.hora %>:<%= @celula.minutos %></dd>
  <dt><strong>Igreja:</strong></dt>
  <dd><%= detalhes2(@celula.igreja, :nome) %></dd>

  <dt><strong>Cordenadores:</strong></dt>
  <dd>
    <% @celula.cordenadores_da_celula.each do |x| %>
      <%= x.nome %><br/>
    <% end %>
  </dd>

  <dt><strong>Supervisores:</strong></dt>
  <dd>
    <% @celula.supervisores_da_celula.each do |x| %>
      <%= x.nome %><br/>
    <% end %>
  </dd>

  <dt><strong>Lideres:</strong></dt>
  <dd>
    <% @celula.lideres_da_celula.each do |x| %>
      <%= x.nome %><br/>
    <% end %>
  </dd>

  <dt><strong>Lideres em Treinamento:</strong></dt>
  <dd>
    <% @celula.lideres_em_treinamento_da_celula.each do |x| %>
      <%= x.nome %><br/>
    <% end %>
  </dd>

  <dt><strong>Membros:</strong></dt>
  <dd>
    <% @celula.membros_da_celula.each do |x| %>
      <%= x.nome %><br/>
    <% end %>
  </dd>

</dl>

<%= link_to link_icone('voltar'),
              celulas_path, :class => 'btn'  %>
<% if can? :update, @celula %>
  <%= link_to link_icone('editar'),
              edit_celula_path(@celula), :class => 'btn btn-default' %>
<% end %>
<% if can? :delete, @celula %> 
  <%= link_to link_icone('desativar'), 
              celula_path(@celula), :class=>"btn btn-danger", method: :delete, data: { confirm: 'Você está certo disso?' } %> 
<% end %>
<% if can? :gerenciar, @celula %>
  <%= link_to "Gerenciar", celula_gerenciar_path(@celula), :class=>"btn btn-default" %> 
<% end %>

<% if can? :create, Celula %>
  <%= link_to link_icone('nova'),
            new_celula_path,
            :class => 'btn btn-primary' %>
<% end %>