config/routes.rb
Rails.application.routes.draw do
  
  resources :tipo_celulas

  get 'relatorios/index'

  get 'relatorios/aniversariantes'

  get 'relatorios/geral'

  resources :trilhos

  resources :celulas do

    get :gerenciar

    get :adicionar_membro

    get :salvar_membro

    get :remover_membro

    get :salvar_lider_em_treinamento

    get :remover_lider_em_treinamento

    get :adicionar_lider

    get :salvar_lider

    get :remover_lider

    get :adicionar_supervisor

    get :salvar_supervisor

    get :remover_supervisor

    get :adicionar_cordenador

    get :salvar_cordenador

    get :remover_cordenador

    get :relatorios

    resources :encontro_semanals, :path => "encontro_semanais" do

      get :enviar

      get :receber

    end

  end

  resources :igrejas

  resources :pessoas do

    get :trilhos

    get :adicionar_trilho

    post :salvar_trilho

    delete :remover_trilho 
    
  end

  devise_for :users
  
  resources :usuarios do

    get :redefinir_senha

    get :logar_como
  
  end 

  get 'home/index'

  get "home/nao_autorizado"

  root 'home#index'

  
end

app/controllers/usuarios_controller.rb
# -*- encoding : utf-8 -*-
class UsuariosController < ApplicationController
  
  load_and_authorize_resource :class=>"User", except: :create
  
  def index
    #@usuarios = usuario.all
    @usuarios = User.accessible_by(current_ability).order_by([:email, :asc])
  end

  def show
    @usuario = User.accessible_by(current_ability).find(params[:id])  
    
  end

  def new
    @usuario = User.new
    
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @usuario }
    end
  end

  def edit
    @usuario = User.accessible_by(current_ability).find(params[:id])
    
  end

  # POST /usuario
  # POST /usuario.json
  def create
    @usuario = User.new(user_params)
    
    respond_to do |format|
      if @usuario.save
        flash[:info] = @@msgs
        format.html { redirect_to usuarios_url }
        format.json { render json: @usuario, status: :created, location: @usuario }
      else
        flash[:danger] = @@msge
        format.html { render action: "new" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
        
      end
    end
  end

  # PUT /usuario/1
  # PUT /usuario/1.json
  def update
    @usuario = User.find(params[:id])

    respond_to do |format|
      if @usuario.update_attributes(user_params)
        flash[:info] = @@msgs
        format.html { redirect_to usuario_url }
        format.json { head :no_content }
      else
        flash[:error] = @@msge
        format.html { render action: "edit" }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuario/1
  # DELETE /usuario/1.json
  def destroy #  -----------------------------------> DESATIVAR / ATIVAR
    @usuario = User.find(params[:id])
    if @usuario.ativo == true
      @usuario.ativo = false
    else
      @usuario.ativo = true
    end
    if @usuario.save!
      flash[:info] = @@msgs
    else
      flash[:dager] = @@msge
    end

    redirect_to usuarios_url
  end

  def logar_como
    if !current_user.nao_master
      sign_in(:user, User.find(params[:usuario_id]))
      redirect_to root_url # or user_root_url
    else
      flash[:info] = "Parece que algo ia dar errado."
      redirect_to root_url # or user_root_url
    end
  end

  def redefinir_senha
    @usuario = User.find(params[:usuario_id])
    @usuario.mudar_senha = true
    @usuario.password = @usuario.password_confirmation = "12345678"
    if @usuario.save(:validate=>false)
      redirect_to usuarios_url, notice: 'Senha redefinida com sucesso. Nova Senha = 12345678'
    else
      redirect_to usuarios_url, alert: 'Senha não foi redefinida, favor checar o cadastro.'
    end
  end

  private   

  def user_params
    params.require(:user).permit(:nome, :igreja_id, :pessoa_id, :ativo, :mudar_senha, :email, :password, :password_confirmation, 
                                                           :sign_in_count, :current_sign_in_at, :last_sign_in_at, :current_sign_in_ip, 
                                                           :last_sign_in_ip, role_ids: [])
  end

end

app/views/usuarios/_user.html.erb
<td><%= link_to user.email, user %></td>

app/views/usuarios/edit.html.erb
<%= titulo_pagina("Editar Usuário","") %>

<%= simple_form_for @usuario, :url=>usuario_path(@usuario) do |f| %>

  <div class="row">
    <div class="col-md-6">
      <%= f.input :nome, :input_html => {:class=>"input-xxlarge", :required=>true} %>    
    </div>
    <div class="col-md-6">
      <%= f.input :email, :input_html => {:class=>"input-xxlarge", :required=>true} %>  
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <% if can? :manage, Role %>
    <%= f.input :role_ids, :label=>"Permissões", :collection=>Role.accessible_by(current_ability).order_by([:nome, :asc]).collect {|d| [d.nome, d.id]}, as: :check_boxes, :input_html => {:class=>"input-xlarge", :required=>true}  %>
  <% end %>
    </div>
    <div class="col-md-6">
      <% @ids = User.where(:pessoa_id.ne=>nil).collect {|p| p.pessoa_id if p.pessoa_id != @usuario.pessoa_id} %>

  <%= f.input :pessoa_id, :label=>"Pessoa Relacionada", :collection=>Pessoa.accessible_by(current_ability).where(:id.nin=>(@ids)).order_by([:nome, :asc]).collect {|p| [p.nome, p.id]}, as: :select, :input_html => {:class=>"col-xs-2", :required=>true}  %> 
    </div>
  </div>

  <% if current_user.igreja_id != nil %>
    <%= f.input :igreja_id, :as => :hidden, :input_html => {value: current_user.igreja.id} %>
  <% else %>
    <%= f.input :igreja_id, :label=>"Igreja", :collection=>Igreja.order_by([:nome, :asc]).collect {|i| [i.nome, i.id]}, as: :select, :input_html => {:class=>"col-xs-2", :required=>true}  %>  
  <% end %>
    
  <br/>

  <div class="form-actions">
    <%= f.button :submit, "Salvar", :class => 'btn-primary' %>
    <%= link_to "Cancelar",
                usuarios_path, :class => 'btn btn-default' %>
  </div>
<% end %>

app/views/usuarios/index.html.erb
<%- model_class = User -%>

<%= titulo_pagina("Listagem de Usuários","") %>


<table id="usuarios" class="display table table-hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th>Pessoa</th>
      <th>Permissões</th>
      <th>Ações</th>
      
    </tr>
  </thead>
  <tbody>
    <% @usuarios.each do |usuario| %>
      <% if usuario.ativo == false %>
        <tr class="danger">
      <% elsif usuario.mudar_senha == true %>
        <tr class="info">
      <% else %>
        <tr>
      <% end %>
        <td><%= usuario.nome %></td>
        <td><%= usuario.email %></td>
        <td><%= detalhes2(usuario.pessoa,:nome) %></td>
        <td>
          <% usuario.roles.each do |r| %>

            <%= icone_permissao(r.nome) %>

          <% end %>
        </td>
        <td>
          <% if usuario.ativo == true %>
            <%= link_to link_icone('detalhes'),
                      usuario_path(usuario), :class => 'btn' %>
            <%= link_to link_icone('editar'),
                      edit_usuario_path(usuario), :class => 'btn btn-default' %>
            <% if can? :delete, usuario %>
              <%= link_to link_icone('desativar'), usuario_path(usuario), :class=>"btn btn-danger", method: :delete, data: { confirm: 'Você está certo disso?' } %> 
            <% end %>
            <% if can? :redefinir_senha, usuario %>
              <%= link_to link_icone('resetar'), usuario_redefinir_senha_path(usuario), :class=>"btn btn-warning", data: { confirm: 'Você está certo disso?' } %>
            <% end %>

            <% if !current_user.nao_master %>
              <%= link_to link_icone('logar'), usuario_logar_como_path(:usuario_id=>usuario.id), :class=>"btn btn-success", data: { confirm: 'Vai logar mesmo?' } %> 
            <% end %> 

          <% else %>            
            <% if can? :delete, usuario %>
              <%= link_to link_icone('ativar'), usuario_path(usuario), :class=>"btn btn-success", method: :delete, data: { confirm: 'Você está certo disso?' } %> 
            <% end %> 
          <% end %>
          
        </td>


      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to link_icone('novo'),
            new_usuario_path,
            :class => 'btn btn-primary' %>

app/views/usuarios/new.html.erb
<%= titulo_pagina("Novo Usuário","") %>

<%= simple_form_for @usuario, :url=>usuarios_path do |f| %>
  
  <div class="row">
    <div class="col-md-6">
      <%= f.input :nome, :input_html => {:class=>"input-xxlarge", :required=>true} %>
    </div>
    <div class="col-md-6">
      <%= f.input :email, :input_html => {:class=>"input-xxlarge", :required=>true} %>
    </div>
  </div>

  <div class="row">
    <div class="col-md-6">
      <% if can? :manage, Role %>
        <%= f.input :role_ids, :label=>"Permissões", :collection=>Role.accessible_by(current_ability).order_by([:nome, :asc]).collect {|d| [d.nome, d.id]}, as: :check_boxes, :input_html => {:class=>"input-xlarge", :required=>true}  %>
      <% end %>
    </div>
    <div class="col-md-6">
      <% @ids = User.where(:pessoa_id.ne=>nil).collect {|p| p.pessoa_id} %>
      <%= f.input :pessoa_id, :label=>"Pessoa Relacionada", :collection=>Pessoa.accessible_by(current_ability).where(:id.nin=>(@ids)).order_by([:nome, :asc]).collect {|p| [p.nome, p.id]}, as: :select, :input_html => {:class=>"col-xs-2", :required=>true}  %>  
    </div>
  </div>

  <% if current_user.igreja_id != nil %>
    <%= f.input :igreja_id, :as => :hidden, :input_html => {value: current_user.igreja.id} %>
  <% else %>
    <%= f.input :igreja_id, :label=>"Igreja", :collection=>Igreja.order_by([:nome, :asc]).collect {|i| [i.nome, i.id]}, as: :select, :input_html => {:class=>"col-xs-2", :required=>true}  %>  
  <% end %>

  <p class="text-danger">Atenção: A senha gerada sera: "12345678"</p>
  <p class="text-info">Apos o primeiro login o usuario sera redirecionado e solicitado a mudar sua senha. <br/>Apos mudar sua senha o usuario tera que efetuar novamente o login.</p>

  <%= f.input :password, :as => :hidden, :input_html => {value: "12345678"} %>
  <%= f.input :password_confirmation, :as => :hidden, :input_html => {value: "12345678"} %>
  
  <br/>

  <div class="form-actions">
    <%= f.button :submit, "Salvar", :class => 'btn btn-primary' %>
    <%= link_to "Cancelar",
                usuarios_path, :class => 'btn btn-default' %>
  </div>

<% end %>

app/views/usuarios/show.html.erb
<%- model_class = User -%>
<%= titulo_pagina("Detalhes do Usuário","") %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @usuario.nome %></dd>
  <dt><strong>Permissão:</strong></dt>
  <dd>
    <% @usuario.roles.each do |r| %>
      <%= r.nome %> 
    <% end %>
  </dd> 
  <dt><strong><%= model_class.human_attribute_name(:ativo) %>:</strong></dt>
  <dd><%= simnao(@usuario.ativo) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:mudar_senha) %>:</strong></dt>
  <dd><%= simnao(@usuario.mudar_senha) %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @usuario.email %></dd>
    
  <dt><strong>Pessoa Relacionada:</strong></dt>
  <dd><%= detalhes2(@usuario.pessoa,:nome) %></dd>

  <dt><strong>Igreja:</strong></dt>
  <dd><%= detalhes2(@usuario.igreja,:nome) %></dd>
  
  <dt><strong>Ultimo login em:</strong></dt>
  <dd><%= @usuario.last_sign_in_at %></dd>
  <dt><strong>Ultimo IP:</strong></dt>
  <dd><%= @usuario.last_sign_in_ip %></dd>
</dl>

<%= link_to link_icone('voltar'),
              usuarios_path, :class => 'btn'  %>
<%= link_to link_icone('editar'),
              edit_usuario_path(@usuario), :class => 'btn btn-default' %>
<%= link_to link_icone('desativar'), 
              usuario_path(@usuario), :class=>"btn btn-danger", method: :delete, data: { confirm: 'Você está certo disso?' } %> 
<%= link_to link_icone('novo'),
            new_usuario_path,
            :class => 'btn btn-primary' %>