config/routes.rb
Rails.application.routes.draw do
  
  resources :tipo_celulas

  get 'relatorios/index'

  get 'relatorios/aniversariantes'

  get 'relatorios/geral'

  resources :trilhos

  resources :celulas do

    get :gerenciar

    get :adicionar_membro

    get :salvar_membro

    get :remover_membro

    get :salvar_lider_em_treinamento

    get :remover_lider_em_treinamento

    get :adicionar_lider

    get :salvar_lider

    get :remover_lider

    get :adicionar_supervisor

    get :salvar_supervisor

    get :remover_supervisor

    get :adicionar_cordenador

    get :salvar_cordenador

    get :remover_cordenador

    get :relatorios

    resources :encontro_semanals, :path => "encontro_semanais" do

      get :enviar

      get :receber

    end

  end

  resources :igrejas

  resources :pessoas do

    get :trilhos

    get :adicionar_trilho

    post :salvar_trilho

    delete :remover_trilho 
    
  end

  devise_for :users
  
  resources :usuarios do

    get :redefinir_senha

    get :logar_como
  
  end 

  get 'home/index'

  get "home/nao_autorizado"

  root 'home#index'

  
end

app/models/tipo_celula.rb
class TipoCelula
  include Mongoid::Document
end

app/controllers/tipo_celulas_controller.rb
class TipoCelulasController < ApplicationController
  before_action :set_tipo_celula, only: [:show, :edit, :update, :destroy]

  # GET /tipo_celulas
  # GET /tipo_celulas.json
  def index
    @tipo_celulas = TipoCelula.all
  end

  # GET /tipo_celulas/1
  # GET /tipo_celulas/1.json
  def show
  end

  # GET /tipo_celulas/new
  def new
    @tipo_celula = TipoCelula.new
  end

  # GET /tipo_celulas/1/edit
  def edit
  end

  # POST /tipo_celulas
  # POST /tipo_celulas.json
  def create
    @tipo_celula = TipoCelula.new(tipo_celula_params)

    respond_to do |format|
      if @tipo_celula.save
        format.html { redirect_to @tipo_celula, notice: 'Tipo celula was successfully created.' }
        format.json { render :show, status: :created, location: @tipo_celula }
      else
        format.html { render :new }
        format.json { render json: @tipo_celula.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tipo_celulas/1
  # PATCH/PUT /tipo_celulas/1.json
  def update
    respond_to do |format|
      if @tipo_celula.update(tipo_celula_params)
        format.html { redirect_to @tipo_celula, notice: 'Tipo celula was successfully updated.' }
        format.json { render :show, status: :ok, location: @tipo_celula }
      else
        format.html { render :edit }
        format.json { render json: @tipo_celula.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tipo_celulas/1
  # DELETE /tipo_celulas/1.json
  def destroy
    @tipo_celula.destroy
    respond_to do |format|
      format.html { redirect_to tipo_celulas_url, notice: 'Tipo celula was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tipo_celula
      @tipo_celula = TipoCelula.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tipo_celula_params
      params[:tipo_celula]
    end
end

app/helpers/tipo_celulas_helper.rb
module TipoCelulasHelper
end

app/views/tipo_celulas/_form.html.erb
<%= simple_form_for(@tipo_celula) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/tipo_celulas/edit.html.erb
<h1>Editing Tipo_celula</h1>

<%= render 'form' %>

<%= link_to 'Show', @tipo_celula %> |
<%= link_to 'Back', tipo_celulas_path %>

app/views/tipo_celulas/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tipo_celulas</h1>

<table id="tipo_celulas" class="display table table-hover" cellspacing="0" width="100%">
  <thead>
    <tr>
      <th>Tipo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tipo_celulas.each do |tipo_celula| %>
      <tr>
        <tr></tr>
        <td><%= link_to 'Show', tipo_celula %>
        <%= link_to 'Edit', edit_tipo_celula_path(tipo_celula) %></td>
        <%= link_to 'Destroy', tipo_celula, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tipo celula', new_tipo_celula_path %>

app/views/tipo_celulas/new.html.erb
<h1>New Tipo_celula</h1>

<%= render 'form' %>

<%= link_to 'Back', tipo_celulas_path %>

app/views/tipo_celulas/show.html.erb
<p id="notice"><%= notice %></p>

<%= link_to 'Edit', edit_tipo_celula_path(@tipo_celula) %> |
<%= link_to 'Back', tipo_celulas_path %>