config/routes.rb
Rails.application.routes.draw do
  
  resources :tipo_celulas

  get 'relatorios/index'

  get 'relatorios/aniversariantes'

  get 'relatorios/geral'

  resources :trilhos

  resources :celulas do

    get :gerenciar

    get :adicionar_membro

    get :salvar_membro

    get :remover_membro

    get :salvar_lider_em_treinamento

    get :remover_lider_em_treinamento

    get :adicionar_lider

    get :salvar_lider

    get :remover_lider

    get :adicionar_supervisor

    get :salvar_supervisor

    get :remover_supervisor

    get :adicionar_cordenador

    get :salvar_cordenador

    get :remover_cordenador

    get :relatorios

    resources :encontro_semanals, :path => "encontro_semanais" do

      get :enviar

      get :receber

    end

  end

  resources :igrejas

  resources :pessoas do

    get :trilhos

    get :adicionar_trilho

    post :salvar_trilho

    delete :remover_trilho 
    
  end

  devise_for :users
  
  resources :usuarios do

    get :redefinir_senha

    get :logar_como
  
  end 

  get 'home/index'

  get "home/nao_autorizado"

  root 'home#index'

  
end

app/views/layouts/_deslogado.html.erb
<%= yield %>

app/views/layouts/_logado.html.erb
<div id="wrapper">

    <%= render 'layouts/navbar' %>

    <div id="page-wrapper">

        <div class="container-fluid">

            <!-- Page Heading -->
            <div class="row">
                <div class="col-lg-12">
                    <h1 class="page-header">
                        <%= yield :titulo %>
                        <small><%= yield :sub_titulo %></small>
                    </h1>
                    
                    <%= render 'layouts/messages' %>
										<%= yield %>

                </div>
            </div>
            <!-- /.row -->

        </div>
        <!-- /.container-fluid -->

    </div>
    <!-- /#page-wrapper -->

</div>
<!-- /#wrapper -->

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="/home/index">EMCELULAS</a>
    </div>
    <!-- Top Menu Items -->
    <ul class="nav navbar-right top-nav">
        
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown"><i class="fa fa-user"></i> <%= current_user.nome %> <b class="caret"></b></a>
            <ul class="dropdown-menu">
            	
                <li>
                    <a href="/users/edit"><i class="fa fa-fw fa-user"></i> Perfil</a>
                </li>
                <li class="divider"></li>
                <li>
                    <a data-method="get" href="/users/sign_out"><i class="fa fa-fw fa-power-off"></i> Sair</a>
                </li>
            </ul>
        </li>
    </ul>

    <%= render 'layouts/sidebar' %>

</nav>

app/views/layouts/_sidebar.html.erb
<!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
<div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
        <li>
            <% if params[:controller].to_s == 'home' %>
                <%= link_to raw("<i class='fa fa-home fa-fw'></i> Home"), root_url, :class=>"active-menu" %>
            <% else %>
                <%= 
                    #link_to raw("<i class='fa fa-home fa-fw'></i> Home"), root_url, :target=>"_blank" para abrir em nova aba
                 %>
                <%= link_to raw("<i class='fa fa-home fa-fw'></i> Home"), root_url %>
            <% end %>
        </li>

                              
        <% if can? :manage, User %>
            <% if can? :manage, Role %>
                <li>
                    
                    <% if params[:controller].to_s == 'usuarios' %>
                        <%= link_to raw("<i class='fa fa-cog fa-fw'></i> Usuários"), usuarios_path, :class=>"active-menu" %>
                    <% else %>    
                        <%= link_to raw("<i class='fa fa-cog fa-fw'></i> Usuários"), usuarios_path %>
                    <% end %>
                </li>
            <% end %>
        <% end %>

        <% if can? :manage, Igreja %>
            
            <li>
                
                <% if params[:controller].to_s == 'igrejas' %>
                    <%= link_to raw("<i class='fa fa-university fa-fw'></i> Igrejas"), igrejas_path, :class=>"active-menu" %>
                <% else %>    
                    <%= link_to raw("<i class='fa fa-university fa-fw'></i> Igrejas"), igrejas_path %>
                <% end %>
            </li>
            
        <% end %>

        
            
        <li>
            
            <% if can? :show, :relatorios %>    
                <% if params[:controller].to_s == 'relatorios' %>
                    <%= link_to raw("<i class='fa fa-file-text-o fa-fw'></i> Relatórios"), relatorios_index_path, :class=>"active-menu" %>
                <% else %>    
                    <%= link_to raw("<i class='fa fa-file-text-o fa-fw'></i> Relatórios"), relatorios_index_path %>
                <% end %>
            <% end %>

        </li>
            
       

        <% if can? :manage, Pessoa %>
            
            <li>
                
                <% if params[:controller].to_s == 'pessoas' %>
                    <%= link_to raw("<i class='fa fa-users fa-fw'></i> Pessoas"), pessoas_path, :class=>"active-menu" %>
                <% else %>    
                    <%= link_to raw("<i class='fa fa-users fa-fw'></i> Pessoas"), pessoas_path %>
                <% end %>
            </li>
            
        <% end %>

        <% if can? :read, Celula %>
            
            <li>
                
                <% if params[:controller].to_s == 'celulas' %>
                    <%= link_to raw("<i class='fa fa-circle-o-notch fa-fw'></i> Células"), celulas_path, :class=>"active-menu" %>
                <% else %>    
                    <%= link_to raw("<i class='fa fa-circle-o-notch fa-fw'></i> Células"), celulas_path %>
                <% end %>
            </li>
            
        <% end %>

        <% if can? :manage, Trilho %>
            
            <li>
                
                <% if params[:controller].to_s == 'trilhos' %>
                    <%= link_to raw("<i class='fa fa-road fa-fw'></i> Trilhos"), trilhos_path, :class=>"active-menu" %>
                <% else %>    
                    <%= link_to raw("<i class='fa fa-road fa-fw'></i> Trilhos"), trilhos_path %>
                <% end %>
            </li>
            
        <% end %>
        
    </ul>
</div>
<!-- /.navbar-collapse -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="pt-BR">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title><%= content_for?(:title) ? yield(:title) : "EMCELULAS" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "EMCELULAS - Sistema de Gerenciamento de Igrejas em Celulas" %>">
    <%= favicon_link_tag 'sicad.png' %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%= csrf_meta_tags %>
  </head>


<body>

    <% if !current_user %>
        <%= render 'layouts/deslogado' %>
    <% else %>
        <%= render 'layouts/logado' %>
    <% end %>

    <%= javascript_include_tag 'application' %>

</body>

</html>